name: tokencut
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.12.2
  - certifi=2022.12.7
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=22.3.1
  - pthread-stubs=0.3
  - python=3.7.16
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.20.3
      - cachetools==5.5.2
      - catalyst==22.4
      - charset-normalizer==3.4.4
      - cycler==0.11.0
      - fonttools==4.38.0
      - google-auth==2.45.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - hydra-slayer==0.5.0
      - idna==3.10
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - networkx==2.6.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opencv-python==4.12.0.88
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - protobuf==3.20.3
      - psutil==7.2.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - six==1.17.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.3.2
      - torch==1.7.1+cu110
      - torchvision==0.8.2+cu110
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - werkzeug==2.2.3
      - zipp==3.15.0
prefix: /home/juyiang/data/conda_envs/tokencut
